### ISSUE TITLE
More than just MYSQL

### ISSUE THREAD

**Issue by carlosdaniel26** [FabioAugustoRodrigues/iMono#2]
I was looking at the code in the database part, and I realized that the only database you can connect to is mysql, it's obvious that php + mysql is like beans and rice, but maybe it would be interesting for you to have the possibility of connect to PostgreSQL for example.

**Comment by FabioAugustoRodrigues** [comment]
Yes, that's true. 
Although I started with MySQL support because it is a common combination, it is important to have support for other databases, including postgresql.

In this case, one should continue with PDO following the singleton approach to establish the connection. I believe that a good option is to add a DB_DRIVER variable in .env and dynamically configure the $dsn, allowing the use of other databases.

The code could look like the following:

- .env:
```
DB_DRIVER=db_driver
DB_HOST=localhost
DB_USER=root
DB_PASS=root
DB_NAME=name
```

- source.php:
```php
...

define("DB_DRIVER", $_ENV['DB_DRIVER']);
define("DB_HOST", $_ENV['DB_HOST']);
define("DB_USER", $_ENV['DB_USER']);
define("DB_PASS", $_ENV['DB_PASS']);
define("DB_NAME", $_ENV['DB_NAME']);
```

- Connection.php:
```php
...

$dsn = sprintf("%s:host=%s;dbname=%s;charset=utf8", DB_DRIVER, DB_HOST, DB_NAME);
self::$connection = new PDO($dsn, DB_USER, DB_PASS);
```

Feel free to share any ideas

**Comment by carlosdaniel26** [comment]
Looks great to me, good idea.
