### ISSUE TITLE
Create a custom error page

### ISSUE THREAD

**Issue by carlosdaniel26** [FabioAugustoRodrigues/iMono#9]
Create a way to configure a error page like a 404 error page without need configure inside of the router class code

**Comment by FabioAugustoRodrigues** [comment]
I don't know if it makes sense, because almost everything is now being controlled by routes
I think we need to see what the templating system will look like to create this error page

but we can see the current code:
when a route doesn't exist we return a json with 404 error code, do you intend to return a html of this?

**Comment by carlosdaniel26** [comment]
Yeah im talking about when its on browser, like have some way to create your own error page

**Comment by FabioAugustoRodrigues** [comment]
In the project we have the release of the standard 404 error page, this update was released in the commit:
https://github.com/FabioAugustoRodrigues/iMono/commit/c7b6eb2974307b3aebc04e036ad5d1627d01f873
<br><br>
However, if the developer decides to create his own error page, he can simply configure a route to redirect that page, for example:
```routes/web.php```
```php
Router::post("/forbidden", ErrorPageController::class, "forbidden");
```
```ErrorPageController``` is a class that the developer must create and implement its logic
